### PR TITLE
Bug 1147296 - Handle CDMA flash command. r=echen

### PR DESCRIPTION
**Pull request by ghost**
Applying this pull requst will make rild has the ability to handle RIL parcel (`RIL_REQUEST_CDMA_FLASH`) by sending the responding AT command (`AT+WFSH`) to the emulator for further handling.

### CODE REVIEW

**Comment by EdgarChen** [comment]
Super nit: s/U/u/ in commit message. :)

**Comment by ghost** [comment]
That's a stupid mistake :P

**Comment by EdgarChen** [comment]
Just a reminder: don't forget to revise the commit message with s/U/u/. ;)

**Comment by ghost** [comment]
Thanks for the reminder, it's updated now :)

**Pull request merged**
